// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.0
// source: pmond/protos/exec_flags.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File          string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	User          string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Log           string   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	LogDir        string   `protobuf:"bytes,4,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	NoAutoRestart bool     `protobuf:"varint,5,opt,name=no_auto_restart,json=noAutoRestart,proto3" json:"no_auto_restart,omitempty"`
	Args          string   `protobuf:"bytes,6,opt,name=args,proto3" json:"args,omitempty"`
	EnvVars       string   `protobuf:"bytes,7,opt,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	Name          string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Dependencies  []string `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Groups        []string `protobuf:"bytes,10,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ExecFlags) Reset() {
	*x = ExecFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pmond_protos_exec_flags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecFlags) ProtoMessage() {}

func (x *ExecFlags) ProtoReflect() protoreflect.Message {
	mi := &file_pmond_protos_exec_flags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecFlags.ProtoReflect.Descriptor instead.
func (*ExecFlags) Descriptor() ([]byte, []int) {
	return file_pmond_protos_exec_flags_proto_rawDescGZIP(), []int{0}
}

func (x *ExecFlags) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ExecFlags) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecFlags) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *ExecFlags) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *ExecFlags) GetNoAutoRestart() bool {
	if x != nil {
		return x.NoAutoRestart
	}
	return false
}

func (x *ExecFlags) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *ExecFlags) GetEnvVars() string {
	if x != nil {
		return x.EnvVars
	}
	return ""
}

func (x *ExecFlags) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecFlags) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ExecFlags) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_pmond_protos_exec_flags_proto protoreflect.FileDescriptor

var file_pmond_protos_exec_flags_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6d, 0x6f, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65,
	0x78, 0x65, 0x63, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x85, 0x02, 0x0a, 0x09,
	0x45, 0x78, 0x65, 0x63, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6c, 0x6f, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x12, 0x26, 0x0a, 0x0f,
	0x6e, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6e, 0x6f, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f,
	0x76, 0x61, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x56,
	0x61, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6d, 0x6f, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pmond_protos_exec_flags_proto_rawDescOnce sync.Once
	file_pmond_protos_exec_flags_proto_rawDescData = file_pmond_protos_exec_flags_proto_rawDesc
)

func file_pmond_protos_exec_flags_proto_rawDescGZIP() []byte {
	file_pmond_protos_exec_flags_proto_rawDescOnce.Do(func() {
		file_pmond_protos_exec_flags_proto_rawDescData = protoimpl.X.CompressGZIP(file_pmond_protos_exec_flags_proto_rawDescData)
	})
	return file_pmond_protos_exec_flags_proto_rawDescData
}

var file_pmond_protos_exec_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pmond_protos_exec_flags_proto_goTypes = []interface{}{
	(*ExecFlags)(nil), // 0: exec_flags.ExecFlags
}
var file_pmond_protos_exec_flags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pmond_protos_exec_flags_proto_init() }
func file_pmond_protos_exec_flags_proto_init() {
	if File_pmond_protos_exec_flags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pmond_protos_exec_flags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pmond_protos_exec_flags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pmond_protos_exec_flags_proto_goTypes,
		DependencyIndexes: file_pmond_protos_exec_flags_proto_depIdxs,
		MessageInfos:      file_pmond_protos_exec_flags_proto_msgTypes,
	}.Build()
	File_pmond_protos_exec_flags_proto = out.File
	file_pmond_protos_exec_flags_proto_rawDesc = nil
	file_pmond_protos_exec_flags_proto_goTypes = nil
	file_pmond_protos_exec_flags_proto_depIdxs = nil
}
